# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7f3e65fe530a5660484a05e9d13d1b707b74e596d60fd2464687801c515e19e626b9bd3876a162419cc040ec449a28ab6b3deb5cf6f35131ae2e2d9020ec7d1

test:
  secret_key_base: b289b742902d39069b5e50eb803230acf666169fb67fd3daaed2ca5f10fe822c03440fb3ca5492e73e7bb9f5979d145a85e85b561d577facd9ad53fc80ffb564

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
